// Ported from Slashy origin/main:mobile/ios-messages-extension/SlashyTokens.swift
// (itself generated by mobile/scripts/generate-slashy-tokens.js from
// mobile/lib/colors.ts, components/nav/navMetrics.ts,
// components/nav/navMaterial.ts and global.css).
//
// Values are copied verbatim. Only the names changed: the namespace is
// `Tokens`, and the nested UIKit palettes are `Palette` / `LightColor` /
// `DarkColor` (Slashy's `Color` / `Text` would shadow SwiftUI's types inside
// `Tokens`). The SwiftUI-facing statics at the bottom of this file are what
// feature code should use.

import SwiftUI
import UIKit

enum Tokens {
    // MARK: - Scale

    /// Control scale by device width. The iPhone 17 Pro (402pt wide) is the
    /// baseline at 1.0, so its controls are Slashy's literal sizes (40, 36,
    /// 48). Wider phones scale up in proportion: the 17 Pro Max (440pt) lands
    /// at about 1.09. Capped so nothing inflates past 1.15. Text size does not
    /// change control sizes.
    /// Read once, on first use from a view body (always the main thread).
    static let uiScale: CGFloat = {
        let width: CGFloat = MainActor.assumeIsolated {
            let bounds = UIApplication.shared.connectedScenes
                .compactMap { ($0 as? UIWindowScene)?.screen.bounds }
                .first
            return bounds.map { min($0.width, $0.height) } ?? 402
        }
        return min(max(width / 402, 1), 1.15)
    }()

    /// A baseline length on this device, snapped to whole pixels (thirds of a
    /// point on a 3x screen) so edges stay crisp while proportions stay exact.
    static func scaled(_ points: CGFloat) -> CGFloat {
        (points * uiScale * 3).rounded() / 3
    }

    private static func dynamic(light: UIColor, dark: UIColor) -> UIColor {
        UIColor { $0.userInterfaceStyle == .dark ? dark : light }
    }

    // MARK: - Colors (lib/colors.ts)
    //
    // Every token resolves light/dark from the trait collection, exactly as
    // `useColors()` picks a palette for the current scheme.

    enum Palette {
        static let foreground = dynamic(
            light: UIColor(red: 0.176471, green: 0.168627, blue: 0.211765, alpha: 1),
            dark: UIColor(red: 0.827451, green: 0.827451, blue: 0.827451, alpha: 1)
        )
        static let foregroundSecondary = dynamic(
            light: UIColor(red: 0.439216, green: 0.427451, blue: 0.47451, alpha: 1),
            dark: UIColor(red: 0.682353, green: 0.682353, blue: 0.698039, alpha: 1)
        )
        static let foregroundMuted = dynamic(
            light: UIColor(red: 0.576471, green: 0.576471, blue: 0.568627, alpha: 1),
            dark: UIColor(red: 0.533333, green: 0.533333, blue: 0.533333, alpha: 1)
        )
        static let foregroundInverse = dynamic(
            light: UIColor(red: 1, green: 1, blue: 1, alpha: 1),
            dark: UIColor(red: 0.098039, green: 0.098039, blue: 0.098039, alpha: 1)
        )
        static let cardTitle = dynamic(
            light: UIColor(red: 0.113725, green: 0.105882, blue: 0.086275, alpha: 1),
            dark: UIColor(red: 0.827451, green: 0.827451, blue: 0.827451, alpha: 1)
        )
        static let cardSubtitle = dynamic(
            light: UIColor(red: 0.372549, green: 0.368627, blue: 0.356863, alpha: 1),
            dark: UIColor(red: 0.607843, green: 0.607843, blue: 0.607843, alpha: 1)
        )
        static let textPrimary = dynamic(
            light: UIColor(red: 0.176471, green: 0.168627, blue: 0.211765, alpha: 1),
            dark: UIColor(red: 0.827451, green: 0.827451, blue: 0.827451, alpha: 1)
        )
        static let textSecondary = dynamic(
            light: UIColor(red: 0.439216, green: 0.427451, blue: 0.47451, alpha: 1),
            dark: UIColor(red: 0.682353, green: 0.682353, blue: 0.698039, alpha: 1)
        )
        static let textMuted = dynamic(
            light: UIColor(red: 0.576471, green: 0.576471, blue: 0.568627, alpha: 1),
            dark: UIColor(red: 0.533333, green: 0.533333, blue: 0.533333, alpha: 1)
        )
        static let textTertiary = dynamic(
            light: UIColor(red: 0.6, green: 0.6, blue: 0.6, alpha: 1),
            dark: UIColor(red: 0.4, green: 0.4, blue: 0.4, alpha: 1)
        )
        static let textIcon = dynamic(
            light: UIColor(red: 0.372549, green: 0.388235, blue: 0.407843, alpha: 1),
            dark: UIColor(red: 0.498039, green: 0.498039, blue: 0.498039, alpha: 1)
        )
        static let iconFill = dynamic(
            light: UIColor(red: 0, green: 0, blue: 0, alpha: 1),
            dark: UIColor(red: 0.827451, green: 0.827451, blue: 0.827451, alpha: 1)
        )
        static let background = dynamic(
            light: UIColor(red: 1, green: 1, blue: 1, alpha: 1),
            dark: UIColor(red: 0.098039, green: 0.098039, blue: 0.098039, alpha: 1)
        )
        /// The drawer sits a step behind the chat: slightly darker in dark
        /// mode, and only barely off white in light mode.
        static let drawerBackground = dynamic(
            light: UIColor(red: 0.972549, green: 0.972549, blue: 0.972549, alpha: 1),
            dark: UIColor(red: 0.066667, green: 0.066667, blue: 0.066667, alpha: 1)
        )
        static let surface = dynamic(
            light: UIColor(red: 0.968627, green: 0.968627, blue: 0.960784, alpha: 1),
            dark: UIColor(red: 0.12549, green: 0.12549, blue: 0.12549, alpha: 1)
        )
        static let hover = dynamic(
            light: UIColor(red: 0, green: 0, blue: 0, alpha: 0.04),
            dark: UIColor(red: 1, green: 1, blue: 1, alpha: 0.06)
        )
        static let selected = dynamic(
            light: UIColor(red: 0, green: 0, blue: 0, alpha: 0.06),
            dark: UIColor(red: 1, green: 1, blue: 1, alpha: 0.06)
        )
        static let overlay = dynamic(
            light: UIColor(red: 0, green: 0, blue: 0, alpha: 0.5),
            dark: UIColor(red: 0, green: 0, blue: 0, alpha: 0.5)
        )
        static let bgPrimary = dynamic(
            light: UIColor(red: 1, green: 1, blue: 1, alpha: 1),
            dark: UIColor(red: 0.098039, green: 0.098039, blue: 0.098039, alpha: 1)
        )
        static let bgHover = dynamic(
            light: UIColor(red: 0, green: 0, blue: 0, alpha: 0.04),
            dark: UIColor(red: 1, green: 1, blue: 1, alpha: 0.06)
        )
        static let bgHoverIcon = dynamic(
            light: UIColor(red: 0, green: 0, blue: 0, alpha: 0.08),
            dark: UIColor(red: 1, green: 1, blue: 1, alpha: 0.08)
        )
        static let bgEmailFocused = dynamic(
            light: UIColor(red: 0.960784, green: 0.960784, blue: 0.960784, alpha: 1),
            dark: UIColor(red: 0.12549, green: 0.12549, blue: 0.12549, alpha: 1)
        )
        static let border = dynamic(
            light: UIColor(red: 0.898039, green: 0.898039, blue: 0.898039, alpha: 1),
            dark: UIColor(red: 1, green: 1, blue: 1, alpha: 0.055)
        )
        static let borderStrong = dynamic(
            light: UIColor(red: 0.819608, green: 0.835294, blue: 0.858824, alpha: 1),
            dark: UIColor(red: 0.333333, green: 0.333333, blue: 0.333333, alpha: 1)
        )
        static let borderDefault = dynamic(
            light: UIColor(red: 0.878431, green: 0.878431, blue: 0.878431, alpha: 1),
            dark: UIColor(red: 0.266667, green: 0.266667, blue: 0.266667, alpha: 1)
        )
        static let borderDivider = dynamic(
            light: UIColor(red: 0.85098, green: 0.85098, blue: 0.85098, alpha: 1),
            dark: UIColor(red: 0.14902, green: 0.14902, blue: 0.14902, alpha: 1)
        )
        static let borderMedium = dynamic(
            light: UIColor(red: 0.854902, green: 0.862745, blue: 0.878431, alpha: 1),
            dark: UIColor(red: 0.266667, green: 0.266667, blue: 0.266667, alpha: 1)
        )
        // File-type colours — Slashy's attachment badge palette.
        static let filePDF = dynamic(
            light: UIColor(red: 0.917647, green: 0.262745, blue: 0.207843, alpha: 1),
            dark: UIColor(red: 0.85098, green: 0.188235, blue: 0.145098, alpha: 1)
        )
        static let fileDocument = dynamic(
            light: UIColor(red: 0.258824, green: 0.521569, blue: 0.956863, alpha: 1),
            dark: UIColor(red: 0.356863, green: 0.607843, blue: 0.956863, alpha: 1)
        )
        static let fileSpreadsheet = dynamic(
            light: UIColor(red: 0.058824, green: 0.615686, blue: 0.345098, alpha: 1),
            dark: UIColor(red: 0.203922, green: 0.658824, blue: 0.32549, alpha: 1)
        )
        static let accent = dynamic(
            light: UIColor(red: 0.266667, green: 0.341176, blue: 0.768627, alpha: 1),
            dark: UIColor(red: 0.486275, green: 0.541176, blue: 0.941176, alpha: 1)
        )
        static let accentHover = dynamic(
            light: UIColor(red: 0.223529, green: 0.286275, blue: 0.670588, alpha: 1),
            dark: UIColor(red: 0.572549, green: 0.611765, blue: 0.94902, alpha: 1)
        )
        static let accentLight = dynamic(
            light: UIColor(red: 0.905882, green: 0.913725, blue: 0.976471, alpha: 1),
            dark: UIColor(red: 0.266667, green: 0.341176, blue: 0.768627, alpha: 0.24)
        )
        static let destructive = dynamic(
            light: UIColor(red: 0.937255, green: 0.266667, blue: 0.266667, alpha: 1),
            dark: UIColor(red: 0.870588, green: 0.333333, blue: 0.313725, alpha: 1)
        )
        static let destructiveLight = dynamic(
            light: UIColor(red: 0.996078, green: 0.886275, blue: 0.886275, alpha: 1),
            dark: UIColor(red: 0.937255, green: 0.266667, blue: 0.266667, alpha: 0.15)
        )
        static let success = dynamic(
            light: UIColor(red: 0.062745, green: 0.72549, blue: 0.505882, alpha: 1),
            dark: UIColor(red: 0.203922, green: 0.827451, blue: 0.6, alpha: 1)
        )
        static let successLight = dynamic(
            light: UIColor(red: 0.819608, green: 0.980392, blue: 0.898039, alpha: 1),
            dark: UIColor(red: 0.062745, green: 0.72549, blue: 0.505882, alpha: 0.15)
        )
        static let warning = dynamic(
            light: UIColor(red: 0.960784, green: 0.619608, blue: 0.043137, alpha: 1),
            dark: UIColor(red: 0.984314, green: 0.74902, blue: 0.141176, alpha: 1)
        )
        static let warningLight = dynamic(
            light: UIColor(red: 0.996078, green: 0.952941, blue: 0.780392, alpha: 1),
            dark: UIColor(red: 0.960784, green: 0.619608, blue: 0.043137, alpha: 0.15)
        )
        static let star = dynamic(
            light: UIColor(red: 0.960784, green: 0.619608, blue: 0.043137, alpha: 1),
            dark: UIColor(red: 0.85098, green: 0.619608, blue: 0.211765, alpha: 1)
        )
        static let reminder = dynamic(
            light: UIColor(red: 0.847059, green: 0.45098, blue: 0.047059, alpha: 1),
            dark: UIColor(red: 0.894118, green: 0.54902, blue: 0.188235, alpha: 1)
        )
        static let swipeRead = dynamic(
            light: UIColor(red: 0.141176, green: 0.513725, blue: 0.886275, alpha: 1),
            dark: UIColor(red: 0.219608, green: 0.576471, blue: 0.929412, alpha: 1)
        )
        static let swipeArchive = dynamic(
            light: UIColor(red: 0.560784, green: 0.396078, blue: 0.690196, alpha: 1),
            dark: UIColor(red: 0.639216, green: 0.47451, blue: 0.768627, alpha: 1)
        )
        static let swipeTrash = dynamic(
            light: UIColor(red: 0.831373, green: 0.298039, blue: 0.278431, alpha: 1),
            dark: UIColor(red: 0.870588, green: 0.376471, blue: 0.356863, alpha: 1)
        )
        static let swipeLabel = dynamic(
            light: UIColor(red: 0.796078, green: 0.568627, blue: 0.184314, alpha: 1),
            dark: UIColor(red: 0.796078, green: 0.568627, blue: 0.184314, alpha: 1)
        )
        static let swipeNext = dynamic(
            light: UIColor(red: 0.345098, green: 0.388235, blue: 0.447059, alpha: 1),
            dark: UIColor(red: 0.478431, green: 0.52549, blue: 0.596078, alpha: 1)
        )
        static let unreadDot = dynamic(
            light: UIColor(red: 0.266667, green: 0.341176, blue: 0.768627, alpha: 1),
            dark: UIColor(red: 0.486275, green: 0.541176, blue: 0.941176, alpha: 1)
        )
        static let reminderDot = dynamic(
            light: UIColor(red: 0.545098, green: 0.360784, blue: 0.964706, alpha: 1),
            dark: UIColor(red: 0.654902, green: 0.545098, blue: 0.980392, alpha: 1)
        )
        static let checkboxChecked = dynamic(
            light: UIColor(red: 0.266667, green: 0.341176, blue: 0.768627, alpha: 1),
            dark: UIColor(red: 0.486275, green: 0.541176, blue: 0.941176, alpha: 1)
        )
        static let composeSurface = dynamic(
            light: UIColor(red: 1, green: 1, blue: 1, alpha: 1),
            dark: UIColor(red: 0.145098, green: 0.145098, blue: 0.145098, alpha: 1)
        )
        static let composeBorder = dynamic(
            light: UIColor(red: 0, green: 0, blue: 0, alpha: 0.1),
            dark: UIColor(red: 1, green: 1, blue: 1, alpha: 0.08)
        )
        static let composeToolbar = dynamic(
            light: UIColor(red: 0.886275, green: 0.894118, blue: 0.909804, alpha: 1),
            dark: UIColor(red: 0.101961, green: 0.101961, blue: 0.105882, alpha: 1)
        )
        static let userBubble = dynamic(
            light: UIColor(red: 0.796078, green: 0.788235, blue: 0.819608, alpha: 1),
            dark: UIColor(red: 0.247059, green: 0.239216, blue: 0.286275, alpha: 1)
        )
        static let skeletonSurface = dynamic(
            light: UIColor(red: 1, green: 1, blue: 1, alpha: 1),
            dark: UIColor(red: 0, green: 0, blue: 0, alpha: 0)
        )
        static let skeletonPulse = dynamic(
            light: UIColor(red: 0.898039, green: 0.905882, blue: 0.921569, alpha: 1),
            dark: UIColor(red: 0.215686, green: 0.215686, blue: 0.215686, alpha: 1)
        )
        static let toggleTrack = dynamic(
            light: UIColor(red: 0, green: 0, blue: 0, alpha: 0.06),
            dark: UIColor(red: 1, green: 1, blue: 1, alpha: 0.282)
        )
        static let toggleThumb = dynamic(
            light: UIColor(red: 1, green: 1, blue: 1, alpha: 1),
            dark: UIColor(red: 1, green: 1, blue: 1, alpha: 1)
        )
        static let dropdownBg = dynamic(
            light: UIColor(red: 1, green: 1, blue: 1, alpha: 1),
            dark: UIColor(red: 0.145098, green: 0.145098, blue: 0.145098, alpha: 1)
        )
        static let dropdownBorder = dynamic(
            light: UIColor(red: 0.898039, green: 0.898039, blue: 0.898039, alpha: 1),
            dark: UIColor(red: 0.192157, green: 0.192157, blue: 0.192157, alpha: 1)
        )
        static let dropdownHover = dynamic(
            light: UIColor(red: 0.968627, green: 0.968627, blue: 0.960784, alpha: 1),
            dark: UIColor(red: 1, green: 1, blue: 1, alpha: 0.06)
        )
        static let sidebarBg = dynamic(
            light: UIColor(red: 0.968627, green: 0.968627, blue: 0.960784, alpha: 1),
            dark: UIColor(red: 0.12549, green: 0.12549, blue: 0.12549, alpha: 1)
        )
        static let sidebarBorder = dynamic(
            light: UIColor(red: 0.898039, green: 0.898039, blue: 0.898039, alpha: 1),
            dark: UIColor(red: 1, green: 1, blue: 1, alpha: 0.055)
        )
        static let sidebarItemBgActive = dynamic(
            light: UIColor(red: 0, green: 0, blue: 0, alpha: 0.06),
            dark: UIColor(red: 1, green: 1, blue: 1, alpha: 0.06)
        )
        static let sidebarItemBgHover = dynamic(
            light: UIColor(red: 0, green: 0, blue: 0, alpha: 0.04),
            dark: UIColor(red: 1, green: 1, blue: 1, alpha: 0.06)
        )
        static let sidebarTextActive = dynamic(
            light: UIColor(red: 0.176471, green: 0.168627, blue: 0.211765, alpha: 1),
            dark: UIColor(red: 0.827451, green: 0.827451, blue: 0.827451, alpha: 1)
        )
        static let sidebarTextInactive = dynamic(
            light: UIColor(red: 0.439216, green: 0.427451, blue: 0.47451, alpha: 1),
            dark: UIColor(red: 0.607843, green: 0.607843, blue: 0.607843, alpha: 1)
        )
        static let sidebarIconActive = dynamic(
            light: UIColor(red: 0.176471, green: 0.168627, blue: 0.211765, alpha: 1),
            dark: UIColor(red: 0.827451, green: 0.827451, blue: 0.827451, alpha: 1)
        )
        static let sidebarIconInactive = dynamic(
            light: UIColor(red: 0.439216, green: 0.427451, blue: 0.47451, alpha: 1),
            dark: UIColor(red: 0.607843, green: 0.607843, blue: 0.607843, alpha: 1)
        )
        static let tooltipBg = dynamic(
            light: UIColor(red: 0.172549, green: 0.172549, blue: 0.168627, alpha: 1),
            dark: UIColor(red: 0.145098, green: 0.145098, blue: 0.145098, alpha: 1)
        )
        static let tooltipText = dynamic(
            light: UIColor(red: 1, green: 1, blue: 1, alpha: 1),
            dark: UIColor(red: 1, green: 1, blue: 1, alpha: 1)
        )
        static let floatingBar = dynamic(
            light: UIColor(red: 1, green: 1, blue: 1, alpha: 1),
            dark: UIColor(red: 0.145098, green: 0.145098, blue: 0.145098, alpha: 1)
        )
        static let floatingBarAction = dynamic(
            light: UIColor(red: 0.941176, green: 0.941176, blue: 0.933333, alpha: 1),
            dark: UIColor(red: 0.12549, green: 0.12549, blue: 0.12549, alpha: 1)
        )
        static let badgePdf = dynamic(
            light: UIColor(red: 0.917647, green: 0.262745, blue: 0.207843, alpha: 1),
            dark: UIColor(red: 0.85098, green: 0.188235, blue: 0.145098, alpha: 1)
        )
        static let badgeDoc = dynamic(
            light: UIColor(red: 0.258824, green: 0.521569, blue: 0.956863, alpha: 1),
            dark: UIColor(red: 0.356863, green: 0.607843, blue: 0.956863, alpha: 1)
        )
        static let badgeSheet = dynamic(
            light: UIColor(red: 0.058824, green: 0.615686, blue: 0.345098, alpha: 1),
            dark: UIColor(red: 0.203922, green: 0.658824, blue: 0.32549, alpha: 1)
        )
        static let badgeSlide = dynamic(
            light: UIColor(red: 0.984314, green: 0.737255, blue: 0.015686, alpha: 1),
            dark: UIColor(red: 0.898039, green: 0.65098, blue: 0, alpha: 1)
        )
        static let badgeArchive = dynamic(
            light: UIColor(red: 0.47451, green: 0.333333, blue: 0.282353, alpha: 1),
            dark: UIColor(red: 0.552941, green: 0.431373, blue: 0.388235, alpha: 1)
        )
        static let badgeAudio = dynamic(
            light: UIColor(red: 1, green: 0.439216, blue: 0.262745, alpha: 1),
            dark: UIColor(red: 1, green: 0.541176, blue: 0.396078, alpha: 1)
        )
        static let badgeVideo = dynamic(
            light: UIColor(red: 0.917647, green: 0.262745, blue: 0.207843, alpha: 1),
            dark: UIColor(red: 0.85098, green: 0.188235, blue: 0.145098, alpha: 1)
        )
        static let badgeCode = dynamic(
            light: UIColor(red: 0.376471, green: 0.490196, blue: 0.545098, alpha: 1),
            dark: UIColor(red: 0.470588, green: 0.564706, blue: 0.611765, alpha: 1)
        )
        static let badgeDesign = dynamic(
            light: UIColor(red: 0.611765, green: 0.152941, blue: 0.690196, alpha: 1),
            dark: UIColor(red: 0.670588, green: 0.278431, blue: 0.737255, alpha: 1)
        )
        static let badgeFont = dynamic(
            light: UIColor(red: 0.270588, green: 0.352941, blue: 0.392157, alpha: 1),
            dark: UIColor(red: 0.376471, green: 0.490196, blue: 0.545098, alpha: 1)
        )
        static let badgeExe = dynamic(
            light: UIColor(red: 0.270588, green: 0.352941, blue: 0.392157, alpha: 1),
            dark: UIColor(red: 0.376471, green: 0.490196, blue: 0.545098, alpha: 1)
        )
        static let badgeDefault = dynamic(
            light: UIColor(red: 0.619608, green: 0.619608, blue: 0.619608, alpha: 1),
            dark: UIColor(red: 0.619608, green: 0.619608, blue: 0.619608, alpha: 1)
        )
    }

    // MARK: - Pinned light values (lib/colors.ts, light)
    //
    // A balloon is rasterized once on the sender's device and read on both
    // ends of the conversation, so a card face pins the light palette
    // instead of resolving a trait that only describes the sender.

    enum LightColor {
        static let foreground = UIColor(red: 0.176471, green: 0.168627, blue: 0.211765, alpha: 1)
        static let foregroundSecondary = UIColor(red: 0.439216, green: 0.427451, blue: 0.47451, alpha: 1)
        static let foregroundMuted = UIColor(red: 0.576471, green: 0.576471, blue: 0.568627, alpha: 1)
        static let foregroundInverse = UIColor(red: 1, green: 1, blue: 1, alpha: 1)
        static let cardTitle = UIColor(red: 0.113725, green: 0.105882, blue: 0.086275, alpha: 1)
        static let cardSubtitle = UIColor(red: 0.372549, green: 0.368627, blue: 0.356863, alpha: 1)
        static let textPrimary = UIColor(red: 0.176471, green: 0.168627, blue: 0.211765, alpha: 1)
        static let textSecondary = UIColor(red: 0.439216, green: 0.427451, blue: 0.47451, alpha: 1)
        static let textMuted = UIColor(red: 0.576471, green: 0.576471, blue: 0.568627, alpha: 1)
        static let textTertiary = UIColor(red: 0.6, green: 0.6, blue: 0.6, alpha: 1)
        static let textIcon = UIColor(red: 0.372549, green: 0.388235, blue: 0.407843, alpha: 1)
        static let iconFill = UIColor(red: 0, green: 0, blue: 0, alpha: 1)
        static let background = UIColor(red: 1, green: 1, blue: 1, alpha: 1)
        static let surface = UIColor(red: 0.968627, green: 0.968627, blue: 0.960784, alpha: 1)
        static let hover = UIColor(red: 0, green: 0, blue: 0, alpha: 0.04)
        static let selected = UIColor(red: 0, green: 0, blue: 0, alpha: 0.06)
        static let overlay = UIColor(red: 0, green: 0, blue: 0, alpha: 0.5)
        static let bgPrimary = UIColor(red: 1, green: 1, blue: 1, alpha: 1)
        static let bgHover = UIColor(red: 0, green: 0, blue: 0, alpha: 0.04)
        static let bgHoverIcon = UIColor(red: 0, green: 0, blue: 0, alpha: 0.08)
        static let bgEmailFocused = UIColor(red: 0.960784, green: 0.960784, blue: 0.960784, alpha: 1)
        static let border = UIColor(red: 0.898039, green: 0.898039, blue: 0.898039, alpha: 1)
        static let borderStrong = UIColor(red: 0.819608, green: 0.835294, blue: 0.858824, alpha: 1)
        static let borderDefault = UIColor(red: 0.878431, green: 0.878431, blue: 0.878431, alpha: 1)
        static let borderDivider = UIColor(red: 0.85098, green: 0.85098, blue: 0.85098, alpha: 1)
        static let borderMedium = UIColor(red: 0.854902, green: 0.862745, blue: 0.878431, alpha: 1)
        static let accent = UIColor(red: 0.266667, green: 0.341176, blue: 0.768627, alpha: 1)
        static let accentHover = UIColor(red: 0.223529, green: 0.286275, blue: 0.670588, alpha: 1)
        static let accentLight = UIColor(red: 0.905882, green: 0.913725, blue: 0.976471, alpha: 1)
        static let destructive = UIColor(red: 0.937255, green: 0.266667, blue: 0.266667, alpha: 1)
        static let destructiveLight = UIColor(red: 0.996078, green: 0.886275, blue: 0.886275, alpha: 1)
        static let success = UIColor(red: 0.062745, green: 0.72549, blue: 0.505882, alpha: 1)
        static let successLight = UIColor(red: 0.819608, green: 0.980392, blue: 0.898039, alpha: 1)
        static let warning = UIColor(red: 0.960784, green: 0.619608, blue: 0.043137, alpha: 1)
        static let warningLight = UIColor(red: 0.996078, green: 0.952941, blue: 0.780392, alpha: 1)
        static let star = UIColor(red: 0.960784, green: 0.619608, blue: 0.043137, alpha: 1)
        static let reminder = UIColor(red: 0.847059, green: 0.45098, blue: 0.047059, alpha: 1)
        static let swipeRead = UIColor(red: 0.141176, green: 0.513725, blue: 0.886275, alpha: 1)
        static let swipeArchive = UIColor(red: 0.560784, green: 0.396078, blue: 0.690196, alpha: 1)
        static let swipeTrash = UIColor(red: 0.831373, green: 0.298039, blue: 0.278431, alpha: 1)
        static let swipeLabel = UIColor(red: 0.796078, green: 0.568627, blue: 0.184314, alpha: 1)
        static let swipeNext = UIColor(red: 0.345098, green: 0.388235, blue: 0.447059, alpha: 1)
        static let unreadDot = UIColor(red: 0.266667, green: 0.341176, blue: 0.768627, alpha: 1)
        static let reminderDot = UIColor(red: 0.545098, green: 0.360784, blue: 0.964706, alpha: 1)
        static let checkboxChecked = UIColor(red: 0.266667, green: 0.341176, blue: 0.768627, alpha: 1)
        static let composeSurface = UIColor(red: 1, green: 1, blue: 1, alpha: 1)
        static let composeBorder = UIColor(red: 0, green: 0, blue: 0, alpha: 0.1)
        static let composeToolbar = UIColor(red: 0.886275, green: 0.894118, blue: 0.909804, alpha: 1)
        static let userBubble = UIColor(red: 0.796078, green: 0.788235, blue: 0.819608, alpha: 1)
        static let skeletonSurface = UIColor(red: 1, green: 1, blue: 1, alpha: 1)
        static let skeletonPulse = UIColor(red: 0.898039, green: 0.905882, blue: 0.921569, alpha: 1)
        static let toggleTrack = UIColor(red: 0, green: 0, blue: 0, alpha: 0.06)
        static let toggleThumb = UIColor(red: 1, green: 1, blue: 1, alpha: 1)
        static let dropdownBg = UIColor(red: 1, green: 1, blue: 1, alpha: 1)
        static let dropdownBorder = UIColor(red: 0.898039, green: 0.898039, blue: 0.898039, alpha: 1)
        static let dropdownHover = UIColor(red: 0.968627, green: 0.968627, blue: 0.960784, alpha: 1)
        static let sidebarBg = UIColor(red: 0.968627, green: 0.968627, blue: 0.960784, alpha: 1)
        static let sidebarBorder = UIColor(red: 0.898039, green: 0.898039, blue: 0.898039, alpha: 1)
        static let sidebarItemBgActive = UIColor(red: 0, green: 0, blue: 0, alpha: 0.06)
        static let sidebarItemBgHover = UIColor(red: 0, green: 0, blue: 0, alpha: 0.04)
        static let sidebarTextActive = UIColor(red: 0.176471, green: 0.168627, blue: 0.211765, alpha: 1)
        static let sidebarTextInactive = UIColor(red: 0.439216, green: 0.427451, blue: 0.47451, alpha: 1)
        static let sidebarIconActive = UIColor(red: 0.176471, green: 0.168627, blue: 0.211765, alpha: 1)
        static let sidebarIconInactive = UIColor(red: 0.439216, green: 0.427451, blue: 0.47451, alpha: 1)
        static let tooltipBg = UIColor(red: 0.172549, green: 0.172549, blue: 0.168627, alpha: 1)
        static let tooltipText = UIColor(red: 1, green: 1, blue: 1, alpha: 1)
        static let floatingBar = UIColor(red: 1, green: 1, blue: 1, alpha: 1)
        static let floatingBarAction = UIColor(red: 0.941176, green: 0.941176, blue: 0.933333, alpha: 1)
        static let badgePdf = UIColor(red: 0.917647, green: 0.262745, blue: 0.207843, alpha: 1)
        static let badgeDoc = UIColor(red: 0.258824, green: 0.521569, blue: 0.956863, alpha: 1)
        static let badgeSheet = UIColor(red: 0.058824, green: 0.615686, blue: 0.345098, alpha: 1)
        static let badgeSlide = UIColor(red: 0.984314, green: 0.737255, blue: 0.015686, alpha: 1)
        static let badgeArchive = UIColor(red: 0.47451, green: 0.333333, blue: 0.282353, alpha: 1)
        static let badgeAudio = UIColor(red: 1, green: 0.439216, blue: 0.262745, alpha: 1)
        static let badgeVideo = UIColor(red: 0.917647, green: 0.262745, blue: 0.207843, alpha: 1)
        static let badgeCode = UIColor(red: 0.376471, green: 0.490196, blue: 0.545098, alpha: 1)
        static let badgeDesign = UIColor(red: 0.611765, green: 0.152941, blue: 0.690196, alpha: 1)
        static let badgeFont = UIColor(red: 0.270588, green: 0.352941, blue: 0.392157, alpha: 1)
        static let badgeExe = UIColor(red: 0.270588, green: 0.352941, blue: 0.392157, alpha: 1)
        static let badgeDefault = UIColor(red: 0.619608, green: 0.619608, blue: 0.619608, alpha: 1)
    }

    /// The dark half, pinned — for the one place a card face needs it
    /// (a chip drawn on a dark ground) without asking the trait.

    enum DarkColor {
        static let foreground = UIColor(red: 0.827451, green: 0.827451, blue: 0.827451, alpha: 1)
        static let foregroundSecondary = UIColor(red: 0.682353, green: 0.682353, blue: 0.698039, alpha: 1)
        static let foregroundMuted = UIColor(red: 0.533333, green: 0.533333, blue: 0.533333, alpha: 1)
        static let foregroundInverse = UIColor(red: 0.098039, green: 0.098039, blue: 0.098039, alpha: 1)
        static let cardTitle = UIColor(red: 0.827451, green: 0.827451, blue: 0.827451, alpha: 1)
        static let cardSubtitle = UIColor(red: 0.607843, green: 0.607843, blue: 0.607843, alpha: 1)
        static let textPrimary = UIColor(red: 0.827451, green: 0.827451, blue: 0.827451, alpha: 1)
        static let textSecondary = UIColor(red: 0.682353, green: 0.682353, blue: 0.698039, alpha: 1)
        static let textMuted = UIColor(red: 0.533333, green: 0.533333, blue: 0.533333, alpha: 1)
        static let textTertiary = UIColor(red: 0.4, green: 0.4, blue: 0.4, alpha: 1)
        static let textIcon = UIColor(red: 0.498039, green: 0.498039, blue: 0.498039, alpha: 1)
        static let iconFill = UIColor(red: 0.827451, green: 0.827451, blue: 0.827451, alpha: 1)
        static let background = UIColor(red: 0.098039, green: 0.098039, blue: 0.098039, alpha: 1)
        static let surface = UIColor(red: 0.12549, green: 0.12549, blue: 0.12549, alpha: 1)
        static let hover = UIColor(red: 1, green: 1, blue: 1, alpha: 0.06)
        static let selected = UIColor(red: 1, green: 1, blue: 1, alpha: 0.06)
        static let overlay = UIColor(red: 0, green: 0, blue: 0, alpha: 0.5)
        static let bgPrimary = UIColor(red: 0.098039, green: 0.098039, blue: 0.098039, alpha: 1)
        static let bgHover = UIColor(red: 1, green: 1, blue: 1, alpha: 0.06)
        static let bgHoverIcon = UIColor(red: 1, green: 1, blue: 1, alpha: 0.08)
        static let bgEmailFocused = UIColor(red: 0.12549, green: 0.12549, blue: 0.12549, alpha: 1)
        static let border = UIColor(red: 1, green: 1, blue: 1, alpha: 0.055)
        static let borderStrong = UIColor(red: 0.333333, green: 0.333333, blue: 0.333333, alpha: 1)
        static let borderDefault = UIColor(red: 0.266667, green: 0.266667, blue: 0.266667, alpha: 1)
        static let borderDivider = UIColor(red: 0.14902, green: 0.14902, blue: 0.14902, alpha: 1)
        static let borderMedium = UIColor(red: 0.266667, green: 0.266667, blue: 0.266667, alpha: 1)
        static let accent = UIColor(red: 0.486275, green: 0.541176, blue: 0.941176, alpha: 1)
        static let accentHover = UIColor(red: 0.572549, green: 0.611765, blue: 0.94902, alpha: 1)
        static let accentLight = UIColor(red: 0.266667, green: 0.341176, blue: 0.768627, alpha: 0.24)
        static let destructive = UIColor(red: 0.870588, green: 0.333333, blue: 0.313725, alpha: 1)
        static let destructiveLight = UIColor(red: 0.937255, green: 0.266667, blue: 0.266667, alpha: 0.15)
        static let success = UIColor(red: 0.203922, green: 0.827451, blue: 0.6, alpha: 1)
        static let successLight = UIColor(red: 0.062745, green: 0.72549, blue: 0.505882, alpha: 0.15)
        static let warning = UIColor(red: 0.984314, green: 0.74902, blue: 0.141176, alpha: 1)
        static let warningLight = UIColor(red: 0.960784, green: 0.619608, blue: 0.043137, alpha: 0.15)
        static let star = UIColor(red: 0.85098, green: 0.619608, blue: 0.211765, alpha: 1)
        static let reminder = UIColor(red: 0.894118, green: 0.54902, blue: 0.188235, alpha: 1)
        static let swipeRead = UIColor(red: 0.219608, green: 0.576471, blue: 0.929412, alpha: 1)
        static let swipeArchive = UIColor(red: 0.639216, green: 0.47451, blue: 0.768627, alpha: 1)
        static let swipeTrash = UIColor(red: 0.870588, green: 0.376471, blue: 0.356863, alpha: 1)
        static let swipeLabel = UIColor(red: 0.796078, green: 0.568627, blue: 0.184314, alpha: 1)
        static let swipeNext = UIColor(red: 0.478431, green: 0.52549, blue: 0.596078, alpha: 1)
        static let unreadDot = UIColor(red: 0.486275, green: 0.541176, blue: 0.941176, alpha: 1)
        static let reminderDot = UIColor(red: 0.654902, green: 0.545098, blue: 0.980392, alpha: 1)
        static let checkboxChecked = UIColor(red: 0.486275, green: 0.541176, blue: 0.941176, alpha: 1)
        static let composeSurface = UIColor(red: 0.145098, green: 0.145098, blue: 0.145098, alpha: 1)
        static let composeBorder = UIColor(red: 1, green: 1, blue: 1, alpha: 0.08)
        static let composeToolbar = UIColor(red: 0.101961, green: 0.101961, blue: 0.105882, alpha: 1)
        static let userBubble = UIColor(red: 0.247059, green: 0.239216, blue: 0.286275, alpha: 1)
        static let skeletonSurface = UIColor(red: 0, green: 0, blue: 0, alpha: 0)
        static let skeletonPulse = UIColor(red: 0.215686, green: 0.215686, blue: 0.215686, alpha: 1)
        static let toggleTrack = UIColor(red: 1, green: 1, blue: 1, alpha: 0.282)
        static let toggleThumb = UIColor(red: 1, green: 1, blue: 1, alpha: 1)
        static let dropdownBg = UIColor(red: 0.145098, green: 0.145098, blue: 0.145098, alpha: 1)
        static let dropdownBorder = UIColor(red: 0.192157, green: 0.192157, blue: 0.192157, alpha: 1)
        static let dropdownHover = UIColor(red: 1, green: 1, blue: 1, alpha: 0.06)
        static let sidebarBg = UIColor(red: 0.12549, green: 0.12549, blue: 0.12549, alpha: 1)
        static let sidebarBorder = UIColor(red: 1, green: 1, blue: 1, alpha: 0.055)
        static let sidebarItemBgActive = UIColor(red: 1, green: 1, blue: 1, alpha: 0.06)
        static let sidebarItemBgHover = UIColor(red: 1, green: 1, blue: 1, alpha: 0.06)
        static let sidebarTextActive = UIColor(red: 0.827451, green: 0.827451, blue: 0.827451, alpha: 1)
        static let sidebarTextInactive = UIColor(red: 0.607843, green: 0.607843, blue: 0.607843, alpha: 1)
        static let sidebarIconActive = UIColor(red: 0.827451, green: 0.827451, blue: 0.827451, alpha: 1)
        static let sidebarIconInactive = UIColor(red: 0.607843, green: 0.607843, blue: 0.607843, alpha: 1)
        static let tooltipBg = UIColor(red: 0.145098, green: 0.145098, blue: 0.145098, alpha: 1)
        static let tooltipText = UIColor(red: 1, green: 1, blue: 1, alpha: 1)
        static let floatingBar = UIColor(red: 0.145098, green: 0.145098, blue: 0.145098, alpha: 1)
        static let floatingBarAction = UIColor(red: 0.12549, green: 0.12549, blue: 0.12549, alpha: 1)
        static let badgePdf = UIColor(red: 0.85098, green: 0.188235, blue: 0.145098, alpha: 1)
        static let badgeDoc = UIColor(red: 0.356863, green: 0.607843, blue: 0.956863, alpha: 1)
        static let badgeSheet = UIColor(red: 0.203922, green: 0.658824, blue: 0.32549, alpha: 1)
        static let badgeSlide = UIColor(red: 0.898039, green: 0.65098, blue: 0, alpha: 1)
        static let badgeArchive = UIColor(red: 0.552941, green: 0.431373, blue: 0.388235, alpha: 1)
        static let badgeAudio = UIColor(red: 1, green: 0.541176, blue: 0.396078, alpha: 1)
        static let badgeVideo = UIColor(red: 0.85098, green: 0.188235, blue: 0.145098, alpha: 1)
        static let badgeCode = UIColor(red: 0.470588, green: 0.564706, blue: 0.611765, alpha: 1)
        static let badgeDesign = UIColor(red: 0.670588, green: 0.278431, blue: 0.737255, alpha: 1)
        static let badgeFont = UIColor(red: 0.376471, green: 0.490196, blue: 0.545098, alpha: 1)
        static let badgeExe = UIColor(red: 0.376471, green: 0.490196, blue: 0.545098, alpha: 1)
        static let badgeDefault = UIColor(red: 0.619608, green: 0.619608, blue: 0.619608, alpha: 1)
    }

    // MARK: - Metrics (components/nav/navMetrics.ts)

    enum Metric {
        static let marginX: CGFloat = 16
        static let listPadX: CGFloat = 16
        static let listGlyph: CGFloat = scaled(28)
        static let listGap: CGFloat = 12
        static let rowH: CGFloat = scaled(42)
        static let rowTallH: CGFloat = scaled(56)
        static let sectionHeaderH: CGFloat = scaled(28)
        static let fieldH: CGFloat = scaled(48)
        static let capsuleBtn: CGFloat = scaled(32)
        static let capsuleGlyph: CGFloat = scaled(20)
        static let capsuleVoiceBtn: CGFloat = scaled(48)
        static let capsuleVoiceGlyph: CGFloat = scaled(24)
        static let chromeRowH: CGFloat = scaled(40)
        static let chromePadBottom: CGFloat = 8
        static let chromeButton: CGFloat = scaled(40)
        static let chromeGlyph: CGFloat = scaled(20)
        static let edgeSolidStop: CGFloat = 0.25
        static let keyboardTail: CGFloat = 14
        static let blurMax: CGFloat = 42
        static let composerPad: CGFloat = 8
        static let composerBtn: CGFloat = scaled(32)
    }

    // MARK: - Material (components/nav/navMaterial.ts)
    //
    // The glass family states its tints, its one rim and its brand here.
    // A surface that paints its own is a bug, in the app and in the
    // extension alike.

    enum Material {
        static let glassTint = dynamic(
            light: UIColor(red: 1, green: 1, blue: 1, alpha: 0.22),
            dark: UIColor(red: 0.145098, green: 0.145098, blue: 0.145098, alpha: 0.55)
        )
        static let subTint = dynamic(
            light: UIColor(red: 1, green: 1, blue: 1, alpha: 0.6),
            dark: UIColor(red: 0.196078, green: 0.196078, blue: 0.196078, alpha: 0.6)
        )
        static let edge = dynamic(
            light: UIColor(red: 0, green: 0, blue: 0, alpha: 0.1),
            dark: UIColor(red: 1, green: 1, blue: 1, alpha: 0.09)
        )
        static let askBubble = dynamic(
            light: UIColor(red: 0.901961, green: 0.901961, blue: 0.901961, alpha: 1),
            dark: UIColor(red: 0.14902, green: 0.14902, blue: 0.164706, alpha: 1)
        )
        static let chip = dynamic(
            light: UIColor(red: 0, green: 0, blue: 0, alpha: 0.07),
            dark: UIColor(red: 1, green: 1, blue: 1, alpha: 0.09)
        )
        static let brand = dynamic(
            light: UIColor(red: 0.266667, green: 0.341176, blue: 0.768627, alpha: 1),
            dark: UIColor(red: 0.486275, green: 0.541176, blue: 0.941176, alpha: 1)
        )
        static let pressWash = dynamic(
            light: UIColor(red: 0, green: 0, blue: 0, alpha: 0.07),
            dark: UIColor(red: 1, green: 1, blue: 1, alpha: 0.12)
        )
        static let surfaceFloor = dynamic(
            light: UIColor(red: 1, green: 1, blue: 1, alpha: 0.22),
            dark: UIColor(red: 0.145098, green: 0.145098, blue: 0.145098, alpha: 0.55)
        )
        static let brandOn = UIColor(red: 1, green: 1, blue: 1, alpha: 1)

        /// Each pair pinned to one scheme — see `LightColor` / `DarkColor`.
        static let glassTintLight = UIColor(red: 1, green: 1, blue: 1, alpha: 0.22)
        static let glassTintDark = UIColor(red: 0.145098, green: 0.145098, blue: 0.145098, alpha: 0.55)
        static let subTintLight = UIColor(red: 1, green: 1, blue: 1, alpha: 0.6)
        static let subTintDark = UIColor(red: 0.196078, green: 0.196078, blue: 0.196078, alpha: 0.6)
        static let edgeLight = UIColor(red: 0, green: 0, blue: 0, alpha: 0.1)
        static let edgeDark = UIColor(red: 1, green: 1, blue: 1, alpha: 0.09)
        static let askBubbleLight = UIColor(red: 0.901961, green: 0.901961, blue: 0.901961, alpha: 1)
        static let askBubbleDark = UIColor(red: 0.14902, green: 0.14902, blue: 0.164706, alpha: 1)
        static let chipLight = UIColor(red: 0, green: 0, blue: 0, alpha: 0.07)
        static let chipDark = UIColor(red: 1, green: 1, blue: 1, alpha: 0.09)
        static let brandLight = UIColor(red: 0.266667, green: 0.341176, blue: 0.768627, alpha: 1)
        static let brandDark = UIColor(red: 0.486275, green: 0.541176, blue: 0.941176, alpha: 1)
        static let pressWashLight = UIColor(red: 0, green: 0, blue: 0, alpha: 0.07)
        static let pressWashDark = UIColor(red: 1, green: 1, blue: 1, alpha: 0.12)
        static let surfaceFloorLight = UIColor(red: 1, green: 1, blue: 1, alpha: 0.22)
        static let surfaceFloorDark = UIColor(red: 0.145098, green: 0.145098, blue: 0.145098, alpha: 0.55)
    }

    // MARK: - Glass (components/nav/GlassSurface.tsx)

    enum Glass {
        static let idleOpacity: Double = 0.02
    }

    // MARK: - Shadows (components/nav/navMaterial.ts)
    //
    // `radius` is the CSS blur halved: a Core Graphics shadow radius is
    // roughly half the equivalent CSS blur.

    struct Shadow: Sendable {
        let x: CGFloat
        let y: CGFloat
        let radius: CGFloat
        let color: UIColor
        var opacity: Double { color.cgColor.alpha }
    }

    enum Elevation {
        static let barShadow = Shadow(x: 0, y: 2, radius: 5, color: UIColor(red: 0, green: 0, blue: 0, alpha: 0.07))
        static let circleShadow = Shadow(x: 0, y: 1, radius: 2.5, color: UIColor(red: 0, green: 0, blue: 0, alpha: 0.07))
        static let cardShadow = Shadow(x: 0, y: 1, radius: 3, color: UIColor(red: 0, green: 0, blue: 0, alpha: 0.05))
        static let controlShadow = Shadow(x: 0, y: 1, radius: 10, color: UIColor(red: 0, green: 0, blue: 0, alpha: 0.12))
        static let inputShadowLight = Shadow(x: 0, y: 2, radius: 14, color: UIColor(red: 0, green: 0, blue: 0, alpha: 0.14))
        static let inputShadowDark = Shadow(x: 0, y: 2, radius: 16, color: UIColor(red: 0, green: 0, blue: 0, alpha: 0.6))
    }

    // MARK: - Typography (global.css @theme, Apple HIG Dynamic Type)

    struct TextStyle: Sendable {
        let size: CGFloat
        let lineHeight: CGFloat
        /// The extra leading SwiftUI's `.lineSpacing` wants: the CSS ratio
        /// resolved against the size, minus the size itself.
        var lineSpacing: CGFloat { (size * lineHeight) - size }
    }

    enum Typography {
        static let caption2 = TextStyle(size: 11, lineHeight: 1.181818)
        static let caption1 = TextStyle(size: 12, lineHeight: 1.333333)
        static let footnote = TextStyle(size: 13, lineHeight: 1.384615)
        static let subhead = TextStyle(size: 15, lineHeight: 1.333333)
        static let callout = TextStyle(size: 16, lineHeight: 1.3125)
        static let body = TextStyle(size: 17, lineHeight: 1.294118)
        static let title3 = TextStyle(size: 20, lineHeight: 1.25)
        static let title2 = TextStyle(size: 22, lineHeight: 1.272727)
        static let title1 = TextStyle(size: 28, lineHeight: 1.214286)
        static let largeTitle = TextStyle(size: 34, lineHeight: 1.205882)
    }
}

// MARK: - SwiftUI colors
//
// The palette the Puma UI reads. Each resolves light/dark from the trait
// collection through the dynamic UIColor it wraps.

extension Tokens {
    static let foreground = Color(uiColor: Palette.foreground)
    static let foregroundSecondary = Color(uiColor: Palette.foregroundSecondary)
    static let foregroundMuted = Color(uiColor: Palette.foregroundMuted)
    static let foregroundInverse = Color(uiColor: Palette.foregroundInverse)
    static let background = Color(uiColor: Palette.background)
    static let drawerBackground = Color(uiColor: Palette.drawerBackground)
    static let surface = Color(uiColor: Palette.surface)
    static let hover = Color(uiColor: Palette.hover)
    static let border = Color(uiColor: Palette.border)
    static let accent = Color(uiColor: Palette.accent)
    static let composeSurface = Color(uiColor: Palette.composeSurface)
    static let destructive = Color(uiColor: Palette.destructive)
    static let filePDF = Color(uiColor: Palette.filePDF)
    static let fileDocument = Color(uiColor: Palette.fileDocument)
    static let fileSpreadsheet = Color(uiColor: Palette.fileSpreadsheet)

    /// The ask bubble (`Material.askBubble`): #E6E6E6 light / #26262A dark.
    static let userBubble = Color(uiColor: Material.askBubble)

    /// RECORD_RED, #E12432 in both schemes.
    static let recording = Color(uiColor: UIColor(red: 0.882353, green: 0.141176, blue: 0.196078, alpha: 1))

    /// Sheet cards: black 5% light / white 7% dark.
    static let cardFill = Color(uiColor: dynamicColor(
        light: UIColor(red: 0, green: 0, blue: 0, alpha: 0.05),
        dark: UIColor(red: 1, green: 1, blue: 1, alpha: 0.07)
    ))

    /// Sheet row press wash: black 5% light / white 6% dark.
    static let pressWash = Color(uiColor: dynamicColor(
        light: UIColor(red: 0, green: 0, blue: 0, alpha: 0.05),
        dark: UIColor(red: 1, green: 1, blue: 1, alpha: 0.06)
    ))

    /// The glass rim and sheet row dividers (`Material.edge`):
    /// rgba(0,0,0,0.10) light / rgba(255,255,255,0.09) dark.
    static let hairline = Color(uiColor: Material.edge)

    private static func dynamicColor(light: UIColor, dark: UIColor) -> UIColor {
        UIColor { $0.userInterfaceStyle == .dark ? dark : light }
    }
}

// MARK: - Type sizes (global.css @theme)

extension Tokens {
    static let footnote: CGFloat = 13
    static let subhead: CGFloat = 15
    static let callout: CGFloat = 16
    static let body: CGFloat = 17
    static let title3: CGFloat = 20
    /// Used semibold.
    static let title: CGFloat = 24
}

// MARK: - Motion

extension Tokens {
    enum Motion {
        /// The push-reveal drawer: 250ms easeInOut.
        static let drawer: Animation = .easeInOut(duration: 0.25)
        /// Composer primary-button swaps.
        static let buttonSwap: Animation = .interpolatingSpring(mass: 0.85, stiffness: 160, damping: 22)
        /// Voice controls sliding in from the right.
        static let voiceIn: Animation = .interpolatingSpring(mass: 0.85, stiffness: 170, damping: 19)
        /// The 140ms glyph crossfade.
        static let crossfade: Animation = .easeInOut(duration: 0.14)
    }
}
